"""Added an is active check to the project

Revision ID: 06baf4b76760
Revises: 5871e79d4212
Create Date: 2025-11-02 15:26:40.709050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06baf4b76760'
down_revision = '5871e79d4212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
