"""Updated Thought model

Revision ID: 2729cc6566b1
Revises: 
Create Date: 2025-11-01 14:18:23.038461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2729cc6566b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('profile_identity_id', sa.Integer(), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('thoughts_project_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('thoughts_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'profile_identities', ['profile_identity_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('thoughts_owner_id_fkey'), 'profiles', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('thoughts_project_id_fkey'), 'projects', ['project_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('profile_identity_id')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
