"""Updated the task model

Revision ID: c018bbbf3b44
Revises: 06baf4b76760
Create Date: 2025-11-03 13:30:19.892604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c018bbbf3b44'
down_revision = '06baf4b76760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE difficulty AS ENUM ('easy', 'medium', 'hard')"
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=True), nullable=False, server_default="medium"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('due_date')

    op.execute(
        "DROP TYPE difficulty"
    )

    # ### end Alembic commands ###
